# Generated by Django 5.0.3 on 2024-04-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profitolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='address_of_user',
        ),
    ]
