# Generated by Django 5.0.3 on 2024-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitolio', '0004_remove_record_address_remove_record_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='current_price',
            new_name='sell_price',
        ),
        migrations.AddField(
            model_name='record',
            name='sell_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
